/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dice.roll;

import dice.roll.Controller.DiceController;

public class App {

    public static void main(String[] args) {
        DiceController userGame = new DiceController();
    }
}
